- hosts: "{{ env }}"
  become: yes
  tasks:
    - name: Deploying Application pods...
      shell: |
        if [ `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep kube-server | wc -l` -gt 0 ]; then  
           echo "deleteing previous application deployment"
           kubectl delete deployment `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep kube-server`
           echo "creating new application deployment"
           kubectl create deployment kube-server --image=aswinkevin/kube-server:{{ build }}
        else 
           echo "Deploying Sampleapp Application"
           kubectl create deployment kube-server --image=aswinkevin/kube-server:{{ build }}
        fi
    - name: deploying service
      shell: |
        if [ `kubectl get svc | grep kube-server-service  | awk '{print $1}' | wc -l` -gt 0 ]; then
           echo "app service found, No actions taken"
        else
           echo "Creating App Services"
           kubectl expose deployment kube-server --name kube-server-service --type NodePort --port 8001 --target-port 80
        fi
    - name: increase replicas
      shell: kubectl scale deploy kube-server --replicas=3
